from types import SimpleNamespace
from unittest.mock import AsyncMock

import pytest

import backend.core.controlled_chat as controlled_chat
from backend.core.controlled_chat import answer_controlled_chat
from backend.core.legal_relevance import ContextCandidate
from backend.core.query_router import QueryClass


class FakeReranker:
    def rerank(self, question, candidates):
        return [
            ContextCandidate(id=candidate.id, text=candidate.text, source=candidate.source, score=1.0 - index / 10)
            for index, candidate in enumerate(candidates)
        ]


@pytest.mark.anyio
async def test_direct_definition_uses_context_retrieval_before_extractive_answer(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.DIRECT_DEFINITION,
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            assert param.mode == "naive"
            assert system_prompt is None
            return "Luật Đường bộ 35/2024/QH15, Điều 2 khoản 5: Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ.\n\nĐiều 4. Chính sách phát triển kết cấu hạ tầng đường bộ."
        raise AssertionError("Direct definition answers must not be regenerated by the LLM")

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Hành lang an toàn đường bộ được xác định từ đâu và nhằm mục đích gì?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert result.startswith("Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ")
    assert "(Điều 2 khoản 5" in result
    assert "Luật Đường bộ 35/2024/QH15" in result
    assert "Căn cứ chính" not in result
    assert "Liên kết pháp lý liên quan" not in result
    assert "Điều 4. Chính sách" not in result
    assert rag.aquery.await_count == 1


@pytest.mark.anyio
async def test_direct_definition_returns_extractive_answer_without_semantic_drift(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.DIRECT_DEFINITION,
    )

    source_text = (
        "Luật Đường bộ 35/2024/QH15, Điều 2 khoản 5: "
        "Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ, "
        "tính từ mép ngoài phần đất để bảo vệ, bảo trì đường bộ ra hai bên "
        "nhằm bảo đảm an toàn giao thông đường bộ, bảo đảm tầm nhìn xe chạy "
        "và hạn chế ảnh hưởng đến môi trường xung quanh."
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            assert param.mode == "naive"
            return source_text
        raise AssertionError("Direct definition answers must not be regenerated by the LLM")

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Hành lang an toàn đường bộ là gì?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert result.startswith("Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ")
    assert "(Điều 2 khoản 5" in result
    assert "Luật Đường bộ 35/2024/QH15" in result
    assert "Căn cứ chính" not in result
    assert "Liên kết pháp lý liên quan" not in result
    assert "Điều 4. Chính sách" not in result
    assert rag.aquery.await_count == 1


@pytest.mark.anyio
async def test_direct_definition_unwraps_json_context_before_rendering(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.DIRECT_DEFINITION,
    )

    raw_context = (
        '```json\n'
        '{"reference_id": "1", "content": "Luật Đường bộ 35/2024/QH15, Điều 2 khoản 5: '
        'Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ."}'
        '\n```'
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            return raw_context
        raise AssertionError("Direct definition answers must not be regenerated by the LLM")

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Hành lang an toàn đường bộ là gì?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert result.startswith("Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ")
    assert "(Điều 2 khoản 5" in result
    assert "Luật Đường bộ 35/2024/QH15" in result
    assert "Căn cứ chính" not in result
    assert "Liên kết pháp lý liên quan" not in result
    assert "Điều 4. Chính sách" not in result
    assert rag.aquery.await_count == 1


@pytest.mark.anyio
async def test_direct_definition_unwraps_consecutive_json_context_before_rendering(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.DIRECT_DEFINITION,
    )

    raw_context = (
        '{"reference_id": "1", "content": "Điều 1. Phạm vi điều chỉnh."} '
        '{"reference_id": "2", "content": "Luật Đường bộ 35/2024/QH15, Điều 2 khoản 5: '
        'Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ."}'
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            return raw_context
        raise AssertionError("Direct definition answers must not be regenerated by the LLM")

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Hành lang an toàn đường bộ là gì?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert result.startswith("Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ")
    assert "(Điều 2 khoản 5" in result
    assert "Luật Đường bộ 35/2024/QH15" in result
    assert "Căn cứ chính" not in result
    assert "Liên kết pháp lý liên quan" not in result
    assert "Điều 4. Chính sách" not in result
    assert rag.aquery.await_count == 1


@pytest.mark.anyio
async def test_relational_query_uses_hybrid_context_retrieval(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.RELATIONAL,
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            assert param.mode == "hybrid"
            assert system_prompt is None
            return "Trách nhiệm của cơ quan quản lý đường bộ bao gồm quản lý, bảo vệ kết cấu hạ tầng đường bộ."
        assert param.mode == "bypass"
        return "Căn cứ chính\nTrách nhiệm..."

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Quy định về hành lang an toàn đường bộ liên quan đến trách nhiệm của cơ quan nào?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert "Trách nhiệm" in result
    assert rag.aquery.await_count == 2


@pytest.mark.anyio
async def test_generated_answer_with_semantic_drift_falls_back_to_extractive_definition(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.RELATIONAL,
    )

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            return "Điều 2 khoản 5: Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ."
        assert param.mode == "bypass"
        return (
            "Căn cứ chính\n"
            "Theo định nghĩa trên, hành lang an toàn đường bộ là vùng đất nằm song song hai bên mặt đường, "
            "được quy hoạch và quản lý cho các phương tiện lưu thông."
        )

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result = await answer_controlled_chat(
        rag=rag,
        message="Quy định về hành lang an toàn đường bộ liên quan đến trách nhiệm của cơ quan nào?",
        stream=False,
        reranker=FakeReranker(),
    )

    assert result.startswith("Hành lang an toàn đường bộ là dải đất dọc hai bên đất của đường bộ")
    assert "(Điều 2 khoản 5" in result
    assert "Theo định nghĩa trên" not in result
    assert "mặt đường" not in result
    assert "được quy hoạch và quản lý" not in result
    assert "các phương tiện lưu thông" not in result
    assert "Căn cứ chính" not in result
    assert rag.aquery.await_count == 2


@pytest.mark.anyio
async def test_controlled_chat_streaming(monkeypatch):
    monkeypatch.setattr(
        controlled_chat,
        "classify_query",
        lambda message: QueryClass.DIRECT_DEFINITION,
    )

    async def fake_stream():
        yield "chunk-1"
        yield "chunk-2"

    async def fake_aquery(query, param=None, system_prompt=None):
        if param.only_need_context:
            return "Điều 2 khoản 5: Hành lang an toàn..."
        assert param.mode == "bypass"
        assert param.stream is True
        return fake_stream()

    rag = SimpleNamespace(aquery=AsyncMock(side_effect=fake_aquery))

    result_stream = await answer_controlled_chat(
        rag=rag,
        message="Hành lang an toàn là gì?",
        stream=True,
        reranker=FakeReranker(),
    )

    chunks = []
    async for chunk in result_stream:
        chunks.append(chunk)

    assert chunks == ["chunk-1", "chunk-2"]
    assert rag.aquery.await_count == 2
